# Generated by Django 5.1.7 on 2025-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbag',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
