# Generated by Django 5.1.7 on 2025-04-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_shop', '0005_product_sold'),
        ('shopping_bag_shop', '0002_alter_shoppingbag_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbagdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_shop.product'),
        ),
    ]
