# Generated by Django 5.1.7 on 2025-04-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0003_shoppingbagdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbagdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
