# Generated by Django 5.1.7 on 2025-04-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0004_shoppingbagdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingbagdetail',
            name='shopping_bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_bag_shop.shoppingbag'),
        ),
    ]
