# Generated by Django 5.1.7 on 2025-04-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0005_alter_shoppingbagdetail_shopping_bag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbag',
            name='total_price',
        ),
    ]
