# Generated by Django 5.1.7 on 2025-04-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0006_remove_shoppingbag_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbagdetail',
            name='price',
        ),
    ]
