# Generated by Django 5.1.7 on 2025-05-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_shop', '0007_remove_shoppingbagdetail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBagShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('post_code', models.CharField(max_length=30, verbose_name='کد پستی')),
                ('ostan', models.CharField(choices=[('کرمان', 'کرمان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('خراسان جنوبی', 'خراسان جنوبی'), ('فارس', 'فارس'), ('خراسان رضوی', 'خراسان رضوی'), ('اصفهان', 'اصفهان'), ('سمنان', 'سمنان'), ('یزد', 'یزد'), ('هرمزگان', 'هرمزگان'), ('خوزستان', 'خوزستان'), ('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('کردستان', 'کردستان'), ('مرکزی', 'مرکزی'), ('خراسان شمالی', 'خراسان شمالی'), ('لرستان', 'لرستان'), ('کرمانشاه', 'کرمانشاه'), ('مازندران', 'مازندران'), ('بوشهر', 'بوشهر'), ('زنجان', 'زنجان'), ('گلستان', 'گلستان'), ('ایلام', 'ایلام'), ('همدان', 'همدان'), ('اردبیل', 'اردبیل'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('قزوین', 'قزوین'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گیلان', 'گیلان'), ('تهران', 'تهران'), ('قم', 'قم'), ('البرز', 'البرز')], max_length=60, verbose_name='استان')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('shopping_bag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_detail', to='shopping_bag_shop.shoppingbag', verbose_name='سبد خرید')),
            ],
        ),
    ]
