# Generated by Django 5.1.7 on 2025-03-12 15:21

import django.db.models.deletion
import product_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color_shop', '0001_initial'),
        ('size_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product_shop.models.upload_image)),
                ('price', models.IntegerField(max_length=20)),
                ('exists', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='color_shop.clothecolor')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='size_shop.clothesize')),
            ],
        ),
    ]
