# Generated by Django 5.1.7 on 2025-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_shop', '0001_initial'),
        ('product_shop', '0002_remove_product_color_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category_shop.category'),
        ),
    ]
