# Generated by Django 5.1.7 on 2025-03-30 11:31

import aboutus_shop.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=aboutus_shop.models.company_logo_upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=aboutus_shop.models.social_logo_upload_image)),
                ('url', models.URLField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus_shop.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('partner_description', models.TextField()),
                ('role_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=aboutus_shop.models.partner_upload_image)),
                ('AboutUs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus_shop.aboutus')),
            ],
        ),
    ]
