# Generated by Django 5.1.7 on 2025-04-02 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='partner',
        ),
        migrations.AddField(
            model_name='link',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='aboutus_shop.aboutus'),
        ),
    ]
