# Generated by Django 5.1.7 on 2025-04-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_shop', '0002_remove_link_partner_link_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='AboutUs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='aboutus_shop.aboutus'),
        ),
    ]
