# Generated by Django 5.1.7 on 2025-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus_shop', '0003_alter_partners_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
